package service

import (
	"context"
	"fmt"
	"testing"

	"provctl/internal/domain"
	"provctl/internal/plan"
	"provctl/internal/system"
	"provctl/internal/system/fake"
)

type cronStore struct {
	subscription domain.Subscription
	jobs         []domain.CronJob
	createErr    error
}

func (store *cronStore) SubscriptionByName(context.Context, string) (domain.Subscription, error) {
	return store.subscription, nil
}
func (store *cronStore) ListCronJobs(context.Context, int64) ([]domain.CronJob, error) {
	return append([]domain.CronJob(nil), store.jobs...), nil
}
func (store *cronStore) CreateCronJob(_ context.Context, job domain.CronJob) (int64, error) {
	if store.createErr != nil {
		return 0, store.createErr
	}
	job.ID = int64(len(store.jobs) + 1)
	store.jobs = append(store.jobs, job)
	return job.ID, nil
}
func (store *cronStore) DeleteCronJob(_ context.Context, _ int64, id int64) error {
	for index, job := range store.jobs {
		if job.ID == id {
			store.jobs = append(store.jobs[:index], store.jobs[index+1:]...)
			return nil
		}
	}
	return fmt.Errorf("not found")
}

func newCronService(store *cronStore, commands system.Commander) CronService {
	return CronService{Commands: commands, Store: store, Executor: plan.Executor{Journal: &subscriptionJournal{}, Locker: subscriptionLocker{}}}
}

func TestCronService_AddWritesGeneratedCrontabAndRecordsJob(t *testing.T) {
	store := &cronStore{subscription: domain.Subscription{ID: 4, Name: "acme", UnixUser: "acme", Status: "active"}}
	commands := &fake.Commander{}
	if _, err := newCronService(store, commands).Add(context.Background(), "acme", "*/5 * * * *", "/usr/bin/true", "health"); err != nil {
		t.Fatal(err)
	}
	if len(store.jobs) != 1 || store.jobs[0].Schedule != "*/5 * * * *" {
		t.Errorf("jobs = %#v", store.jobs)
	}
	if len(commands.Calls) != 2 || commands.Calls[0].Args[2] != "-l" || !commands.Calls[1].HasStdin {
		t.Errorf("commands = %#v", commands.Calls)
	}
}

func TestCronService_RemoveRewritesCrontabAndDeletesJob(t *testing.T) {
	store := &cronStore{subscription: domain.Subscription{ID: 4, Name: "acme", UnixUser: "acme", Status: "active"}, jobs: []domain.CronJob{{ID: 9, SubscriptionID: 4, Schedule: "@daily", Command: "/usr/bin/true", Enabled: true}}}
	commands := &fake.Commander{}
	if _, err := newCronService(store, commands).Remove(context.Background(), "acme", 9); err != nil {
		t.Fatal(err)
	}
	if len(store.jobs) != 0 || len(commands.Calls) != 2 || !commands.Calls[1].HasStdin {
		t.Errorf("jobs=%#v commands=%#v", store.jobs, commands.Calls)
	}
}

func TestCronService_AddRestoresCrontabWhenMetadataWriteFails(t *testing.T) {
	store := &cronStore{subscription: domain.Subscription{ID: 4, Name: "acme", UnixUser: "acme", Status: "active"}, createErr: fmt.Errorf("SQLite unavailable")}
	commands := &fake.Commander{}
	if _, err := newCronService(store, commands).Add(context.Background(), "acme", "@daily", "/usr/bin/true", ""); err == nil {
		t.Fatal("Add() succeeded despite metadata error")
	}
	if len(commands.Calls) != 3 || !commands.Calls[2].HasStdin {
		t.Errorf("commands = %#v, want read, write, and restoration", commands.Calls)
	}
}

func TestRenderCrontab_SkipsDisabledJobs(t *testing.T) {
	got := renderCrontab([]domain.CronJob{{Schedule: "@daily", Command: "/usr/bin/true", Enabled: true, Comment: "health"}, {Schedule: "@hourly", Command: "/usr/bin/false", Enabled: false}})
	want := "# GENERATED BY PROVCTL - DO NOT EDIT\n@daily /usr/bin/true # health\n"
	if got != want {
		t.Errorf("renderCrontab() = %q, want %q", got, want)
	}
}
